### PR TITLE
Acmapp 71 create user exceptions

### LINKED ISSUE #71: ACMAPP: Create Exceptions for User Not Found and Password Invalid
Create exceptions for REST services if user is not found by the DAO or if the password does not match.

It could say something like User not found for id: <NUMBER> and User not found for username: <NAME>"

Dependency for #73

### LINKED ISSUE #73: ACMAPP: Implement User Exceptions
Install User Not Found and Password Invalid exceptions in REST services.

Dependent on #71 and #16

### PR DESCRIPTION
**Pull request by kwinborne**
Created and implemented user exceptions.

Closes #73 
Closes #71 

Dependent on #53

### CODE REVIEW

**Comment by kwinborne** [comment]
Commit 08d7fbd55067a53804b22148ab7b3e8fc30186ff fixes checks

File: src/test/java/com/acm/jwt/auth/controller/AuthenticationControllerTest.java [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+    }
+
+    @Test
+    void testBrokenTokenDecode() throws MalformedJwtException
+    {
+        Assertions.assertThrows(MalformedJwtException.class,()->{
+        String notAToken="jfkldsjfklasd";
+        Claims brokenToken = authController.decodeToken(notAToken);});
+    }
+}
```
Comment (sambutler1017) [inline src/test/java/com/acm/jwt/auth/controller/AuthenticationControllerTest.java:95]: These two test that do testing of the jwt token should be in the JWTtokenUtilTest class not this one

File: src/main/java/com/acm/jwt/auth/service/AuthenticationService.java [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+     * @param password - Password entered at login.
+     * @return requestedUser - the user which matches the credentials above.
+     * @throws Exception - Throw an exception if the credentials do not match.
+     */
+    public User verifyUser(String username, String password) throws Exception
+    {
+        UserGetRequest request = new UserGetRequest();
+        request.setUsername(username);
+        User requestedUser = userClient.getUserCredentials(request);
+        String hashedPass = PasswordHash.hashPassword(password);
```
Comment (sambutler1017) [inline src/main/java/com/acm/jwt/auth/service/AuthenticationService.java:38]: This is not being used. Delete it

File: src/main/java/com/acm/jwt/auth/service/AuthenticationService.java [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+ * in the database. If correct credentials are passed, it will grant access to the user requested.
+ *
+ * @author Kiyle Winborne
+ * @since 8/2/2020
+ */
+@Component
+public class AuthenticationService
+{
+
+
```
Comment (sambutler1017) [inline src/main/java/com/acm/jwt/auth/service/AuthenticationService.java:22]: Remove these spaces

File: src/main/java/com/acm/jwt/auth/service/AuthenticationService.java [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+    @Autowired
+    private UserClient userClient;
+
+    /**
+     *
```
Comment (sambutler1017) [inline src/main/java/com/acm/jwt/auth/service/AuthenticationService.java:27]: Needs a description

File: src/main/java/com/acm/jwt/auth/controller/AuthenticationController.java [hunk 5]
```diff
@@ -37,4 +50,15 @@
 
     }
 
+    /**
+     *
```
Comment (sambutler1017) [inline src/main/java/com/acm/jwt/auth/controller/AuthenticationController.java:54]: Needs description

File: src/main/java/com/acm/jwt/auth/controller/AuthenticationController.java [hunk 6]
```diff
@@ -16,19 +15,33 @@
...
 {
     @Autowired
     private JwtTokenUtil jwtTokenUtil;
 
     @Autowired
-    private AuthorizationService auth;
+    private AuthenticationService auth;
 
+    /**
+     *
```
Comment (sambutler1017) [inline src/main/java/com/acm/jwt/auth/controller/AuthenticationController.java:38]: Missing Description

File: src/main/java/com/acm/app/user/dao/UserDAO.java [hunk 7]
```diff
@@ -36,7 +36,8 @@
 	 * @param request {@link UserGetRequest} object to search upon
 	 * @return List of {@link User}
 	 */
-	public List<User> getUser(UserGetRequest request) {
+	public List<User> getUser(UserGetRequest request)
+	{
```
Comment (JosueVanDyke) [inline src/main/java/com/acm/app/user/dao/UserDAO.java:40]: Wrong style braces.

File: src/main/java/com/acm/jwt/auth/service/AuthenticationService.java (hunk 2 above)
Comment (kwinborne) [reply src/main/java/com/acm/jwt/auth/service/AuthenticationService.java:38]: Define "this".
If this entire block is deleted, it will break the entire class.

Comment (sambutler1017) [reply src/main/java/com/acm/jwt/auth/service/AuthenticationService.java]: The `hashedPass` variable is not being used

Comment (kwinborne) [reply src/main/java/com/acm/jwt/auth/service/AuthenticationService.java]: Gotcha. Fixed
